### ISSUE TITLE
Issue with helm charts that have [[ in the templates

### ISSUE THREAD

**Issue by paurosello** [giantswarm/architect#339]
When trying to template a HELM chart that contains the templating characters in one of the templates like and is not meant to be replaced:
`      format /^(?<time>[^ ]* [^ ,]*)[^\[]*\[[^\]]*\]\[(?<severity>[^ \]]*) *\] (?<message>.*)$/`

There is an error when using the architect:
```
bash-5.0# architect helm template --dir ./helm/fluentd-elasticsearch
2019/10/15 08:08:07 templating helm chart
dir: ./helm/fluentd-elasticsearch
sha: e7c110edd33c8b0e34061796e5f36edf68f0899f
tag: 
version: 0.2.2-e7c110edd33c8b0e34061796e5f36edf68f0899f
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x73fd81]

goroutine 1 [running]:
text/template.errRecover(0xc0001954e0)
	/usr/local/go/src/text/template/exec.go:164 +0x1cb
panic(0xac3680, 0x1145cd0)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
text/template.(*Template).execute(0x0, 0xc77900, 0xc00022ad50, 0xaf9360, 0xc00023a220, 0x0, 0x0)
	/usr/local/go/src/text/template/exec.go:218 +0x1c1
text/template.(*Template).Execute(...)
	/usr/local/go/src/text/template/exec.go:204
github.com/giantswarm/architect/template.TemplateHelmChartTask.Run.func1(0xc000280300, 0x34, 0xc8b440, 0xc000292410, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/giantswarm/architect/template/helm.go:64 +0x2a6
github.com/giantswarm/architect/vendor/github.com/spf13/afero.walk(0xc8f5c0, 0x117ef50, 0xc000280300, 0x34, 0xc8b440, 0xc000292410, 0xc0001958d8, 0x0, 0x0)
	/go/src/github.com/giantswarm/architect/vendor/github.com/spf13/afero/path.go:44 +0x77
github.com/giantswarm/architect/vendor/github.com/spf13/afero.walk(0xc8f5c0, 0x117ef50, 0xc000248240, 0x24, 0xc8b440, 0xc0002371e0, 0xc0001958d8, 0x0, 0x0)
	/go/src/github.com/giantswarm/architect/vendor/github.com/spf13/afero/path.go:69 +0x3fc
github.com/giantswarm/architect/vendor/github.com/spf13/afero.walk(0xc8f5c0, 0x117ef50, 0x7ffffd4d5868, 0x1c, 0xc8b440, 0xc000236680, 0xc0001958d8, 0x0, 0x203000)
	/go/src/github.com/giantswarm/architect/vendor/github.com/spf13/afero/path.go:69 +0x3fc
github.com/giantswarm/architect/vendor/github.com/spf13/afero.Walk(0xc8f5c0, 0x117ef50, 0x7ffffd4d5868, 0x1c, 0xc0001958d8, 0xb8, 0x0)
	/go/src/github.com/giantswarm/architect/vendor/github.com/spf13/afero/path.go:105 +0xe5
github.com/giantswarm/architect/template.TemplateHelmChartTask.Run(0xc8f5c0, 0x117ef50, 0x7ffffd4d5868, 0x1c, 0xc0000eec30, 0x28, 0xc000248090, 0x2e, 0x1157520, 0xc0001959c0)
	/go/src/github.com/giantswarm/architect/template/helm.go:43 +0xd1
github.com/giantswarm/architect/cmd/helm/template.runTemplateError(0x114f600, 0xc0001dfba0, 0x0, 0x2, 0x0, 0x0)
	/go/src/github.com/giantswarm/architect/cmd/helm/template/runner.go:36 +0x440
github.com/giantswarm/architect/vendor/github.com/spf13/cobra.(*Command).execute(0x114f600, 0xc0001dfb40, 0x2, 0x2, 0x114f600, 0xc0001dfb40)
	/go/src/github.com/giantswarm/architect/vendor/github.com/spf13/cobra/command.go:762 +0x460
github.com/giantswarm/architect/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x114e300, 0xc0000d0058, 0x0, 0x0)
	/go/src/github.com/giantswarm/architect/vendor/github.com/spf13/cobra/command.go:852 +0x2ea
github.com/giantswarm/architect/vendor/github.com/spf13/cobra.(*Command).Execute(...)
	/go/src/github.com/giantswarm/architect/vendor/github.com/spf13/cobra/command.go:800
main.main()
	/go/src/github.com/giantswarm/architect/main.go:10 +0x31
```

Example execution in [circleCI](https://circleci.com/gh/giantswarm/fluentd-elasticsearch)
Helm chart [repo](https://github.com/giantswarm/fluentd-elasticsearch)

**Comment by paurosello** [comment]
moved to giantswarm
